"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";
import "./globals.css";
import { ApolloProviders } from "@/components/providers";
import { useUser } from "@auth0/nextjs-auth0";
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Lief Demo Project",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = useUser();

  useEffect(() => {
    if (user?.email) {
      fetch("/api/login");
    }
  }, [user]);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
        <ApolloProviders>
          <AntdRegistry>{children}</AntdRegistry>
        </ApolloProviders>
      </body>
    </html>
  );
}
